"$schema" = 'https://starship.rs/config-schema.json'

#
# for symbols/glyphs, look here: https://nerdfonts.ytyng.com/
#

#
# my stuff
#

right_format = '${custom.prefect}$terraform $kubernetes $aws'

# Inserts a blank line between shell prompts
add_newline = false

# Disable the line break between the first and second prompt lines
[line_break]
disabled = true

[cmd_duration]
format = '[⏲ $duration]($style) '
min_time = 2_000
show_milliseconds = false

[character]
format = '$symbol '
success_symbol = '[󰚺](bold green)'
error_symbol = '[󰚺](bold red)'
vimcmd_symbol = '[󰧘](bold green)'
vimcmd_visual_symbol = '[󰧘](bold yellow)'
vimcmd_replace_symbol = '[󰧘](bold purple)'
vimcmd_replace_one_symbol = '[󰧘](bold purple)'
disabled = false

[directory]
style = 'blue'
read_only = ' '

#
# apps
#

[aws]
format = '[$symbol($profile )(\($region\) )(\[$duration\])]($style)'
symbol = ' '
style = '#ffb84d'
[aws.region_aliases]
eu-west-1 = 'eu'
us-east-1 = 'us'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = ' '
style = '#AAAAAA'

[git_status]
style = 'red'
# deleted = 'X'

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = 'yellow'

[kubernetes]
disabled = false
format = '[$symbol$context]($style)'
style = '#6f98ed'

[os]
disabled = true
[os.symbols]
Macos = " "

[package]
format = '[$symbol$version]($style) '
symbol = '󰏗 '
style = 'yellow'

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = ' '
version_format = 'v${major}.${minor}'
#python_binary = [["uv", "run", "--no-python-downloads", "python"]]

[terraform]
format = '[$symbol $workspace]($style)'
symbol = ''
style = '#a37ad0'

#
# custom apps
#

[custom.prefect]
command = "cat ~/.prefect/profiles.toml | grep active | awk -F'\"' '{print $2}'"
when = 'true'  
symbol = ' '
style = '#666666'
